version: 2

sources:
  - name: raw
    database: viknesh-497915
    schema: movielens_raw

    tables:
      - name: raw_movies
      - name: raw_ratings
      - name: raw_tags
      - name: raw_links
      - name: raw_genome_scores
      - name: raw_genome_tags